import { useCallback, useEffect, useState, type ReactNode } from 'react';
import { Link } from 'react-router-dom';
import {
  AccessDeniedState,
  AtlasCard,
  EmptyState,
  ErrorState,
  LoadingState,
  StatusChip,
} from '@hvcg/atlas-design-system';
import {
  Button,
  Caption1,
  Text,
  Tab,
  TabList,
  MessageBar,
  MessageBarBody,
  MessageBarTitle,
} from '@fluentui/react-components';
import { ModuleScaffold } from './shared/ModuleScaffold';
import {
  fetchMyWork,
  HubHttpError,
  patchPmTask,
  type MyWork,
  type PmTask,
} from '../integrations/hub/pmApi';
import { useHubAuth } from '../integrations/hub/useHubAuth';
import { projectDetailPath } from '../routing/projectId';
import { isCanonicalClientCode } from '../security/clientCode';
import { ATLAS_STATUS, atlasStatusTone } from '../ui/statusLanguage';

type Bucket =
  | 'today'
  | 'overdue'
  | 'dueThisWeek'
  | 'upcoming'
  | 'waitingOnOthers'
  | 'needsOwnerDecision'
  | 'highValueOpportunities'
  | 'clientEmergencies'
  | 'autoGenerated'
  | 'delegatedToTeam'
  | 'delegatedToAgents'
  | 'requiringApproval'
  | 'recentlyCompleted';

const BUCKET_LABEL: Record<Bucket, string> = {
  overdue: ATLAS_STATUS.overdue,
  today: ATLAS_STATUS.needsAction,
  dueThisWeek: 'This week',
  upcoming: 'Upcoming',
  waitingOnOthers: ATLAS_STATUS.waiting,
  needsOwnerDecision: ATLAS_STATUS.decisionRequired,
  clientEmergencies: ATLAS_STATUS.atRisk,
  highValueOpportunities: 'Opportunities',
  autoGenerated: 'Auto',
  delegatedToTeam: 'Team',
  delegatedToAgents: 'Agents',
  requiringApproval: 'Approvals',
  recentlyCompleted: ATLAS_STATUS.complete,
};

const STACK_LINE = /\n\s*at\s+/;

type RecordRefs = {
  projectId?: string;
  clientCode?: string;
  clientId?: string;
};

type HubFollowUp = RecordRefs & {
  id: string;
  whatIsNeeded: string;
  owedByName?: string;
  nextFollowUpDate?: string;
};

function operatorMessage(err: unknown, fallback: string): string {
  const raw = err instanceof Error ? err.message : String(err || '');
  const first = raw.split('\n')[0].replace(/^Error:\s*/i, '').trim();
  if (!first || STACK_LINE.test(raw) || /^\s*at\s+/.test(first)) return fallback;
  if (first.length > 220) return fallback;
  return first;
}

function isAuthzFailure(err: unknown): boolean {
  if (err instanceof HubHttpError && (err.status === 401 || err.status === 403)) return true;
  const msg = String((err as Error)?.message || err || '');
  return /microsoft sign-in required|bearer token missing|unauthorized|forbidden|\b401\b|\b403\b/i.test(msg);
}

function isOwnerDecisionTask(task: PmTask): boolean {
  const status = (task.status || '').toLowerCase();
  return status === 'needs_owner_approval' || status === 'needs_review';
}

function clientRecordPath(code: string | undefined | null): string | null {
  const raw = String(code || '').trim();
  if (!isCanonicalClientCode(raw)) return null;
  return `/clients/${encodeURIComponent(raw)}`;
}

/** Named destination. Never `/my-work`. */
function taskRecordPath(task: PmTask, bucket: Bucket): string | null {
  const project = projectDetailPath(task.projectId);
  if (project) return project;
  if (isOwnerDecisionTask(task) || bucket === 'needsOwnerDecision' || bucket === 'requiringApproval') {
    return '/tasks';
  }
  return null;
}

function waitingRecordPath(row: RecordRefs): string | null {
  const project = projectDetailPath(row.projectId);
  if (project) return project;
  return clientRecordPath(row.clientCode) || clientRecordPath(row.clientId);
}

function atlasTaskLabel(task: PmTask, bucket: Bucket): string {
  const status = (task.status || '').toLowerCase();
  if (status === 'blocked') return ATLAS_STATUS.blocked;
  if (status === 'waiting') return ATLAS_STATUS.waiting;
  if (status === 'completed') return ATLAS_STATUS.complete;
  if (status === 'needs_owner_approval' || status === 'needs_review') return ATLAS_STATUS.decisionRequired;
  if (bucket === 'overdue') return ATLAS_STATUS.overdue;
  if (bucket === 'waitingOnOthers') return ATLAS_STATUS.waiting;
  if (bucket === 'needsOwnerDecision' || bucket === 'requiringApproval') return ATLAS_STATUS.decisionRequired;
  if (bucket === 'clientEmergencies') return ATLAS_STATUS.atRisk;
  if (bucket === 'recentlyCompleted') return ATLAS_STATUS.complete;
  return BUCKET_LABEL[bucket];
}

function RecordTitle({ to, children }: { to: string | null | undefined; children: ReactNode }) {
  if (to) {
    return (
      <Link to={to}>
        <Text weight="semibold">{children}</Text>
      </Link>
    );
  }
  return <Text weight="semibold">{children}</Text>;
}

function TaskList({
  tasks,
  bucket,
  emptyTitle,
  onComplete,
}: {
  tasks: PmTask[];
  bucket: Bucket;
  emptyTitle: string;
  onComplete: (task: PmTask) => void;
}) {
  if (!tasks.length) return <EmptyState title={emptyTitle} description="Hub returned an empty list for this queue." />;
  return (
    <div>
      {tasks.map((t) => {
        const label = atlasTaskLabel(t, bucket);
        const path = taskRecordPath(t, bucket);
        return (
          <div
            key={t.id}
            style={{
              display: 'grid',
              gridTemplateColumns: '1fr auto',
              gap: 8,
              padding: '10px 0',
              borderBottom: '1px solid color-mix(in srgb, currentColor 10%, transparent)',
            }}
          >
            <div>
              <RecordTitle to={path}>{t.title}</RecordTitle>
              <Caption1 style={{ display: 'block' }}>
                {[t.clientName, t.dueDate, t.assigneeName, t.source].filter(Boolean).join(' · ')}
              </Caption1>
              {t.nextAction ? <Caption1>Next: {t.nextAction}</Caption1> : null}
              {t.blocker ? (
                <Caption1>
                  {ATLAS_STATUS.blocked}: {t.blocker}
                </Caption1>
              ) : null}
            </div>
            <div style={{ display: 'flex', gap: 6 }}>
              <StatusChip tone={atlasStatusTone(label)} label={label} />
              {t.status !== 'completed' ? (
                <Button size="small" onClick={() => onComplete(t)}>
                  Complete
                </Button>
              ) : null}
            </div>
          </div>
        );
      })}
    </div>
  );
}

export function MyWorkPage() {
  const auth = useHubAuth();
  const [work, setWork] = useState<MyWork | null>(null);
  const [tab, setTab] = useState<Bucket>('overdue');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [unauthorized, setUnauthorized] = useState<string | null>(null);
  const [actionError, setActionError] = useState<string | null>(null);

  const refresh = useCallback(async () => {
    if (!auth.tokenReady) return;
    if (!auth.hasBearer) {
      setLoading(false);
      setWork(null);
      setError(null);
      setUnauthorized('Authenticated access required. Sign in with Microsoft to load My Work.');
      return;
    }
    setLoading(true);
    setError(null);
    setUnauthorized(null);
    setActionError(null);
    try {
      const res = await fetchMyWork(auth);
      setWork(res.myWork);
    } catch (err) {
      setWork(null);
      if (isAuthzFailure(err)) {
        setUnauthorized(
          operatorMessage(
            err,
            err instanceof HubHttpError && err.status === 403
              ? 'You are signed in but not entitled to My Work. Hub data is not shown.'
              : 'Authenticated access required. Sign in with Microsoft to load My Work.',
          ),
        );
      } else {
        setError(operatorMessage(err, 'My Work could not be loaded from Hub.'));
      }
    } finally {
      setLoading(false);
    }
  }, [auth]);

  useEffect(() => {
    void refresh();
  }, [refresh]);

  const complete = async (task: PmTask) => {
    try {
      setActionError(null);
      await patchPmTask(auth, task.id, { status: 'completed', ...(task.etag ? { etag: task.etag } : {}) });
      await refresh();
    } catch (err) {
      setActionError(operatorMessage(err, 'Update failed. The Hub record was not changed.'));
    }
  };

  const buckets: Array<{ id: Bucket; label: string; count: number }> = work
    ? [
        { id: 'overdue', label: BUCKET_LABEL.overdue, count: work.overdue.length },
        { id: 'today', label: BUCKET_LABEL.today, count: work.today.length },
        { id: 'waitingOnOthers', label: BUCKET_LABEL.waitingOnOthers, count: work.waitingOnOthers.length },
        { id: 'needsOwnerDecision', label: BUCKET_LABEL.needsOwnerDecision, count: work.needsOwnerDecision.length },
        { id: 'recentlyCompleted', label: BUCKET_LABEL.recentlyCompleted, count: work.recentlyCompleted.length },
      ]
    : [];

  const list = (work?.[tab] as PmTask[] | undefined) || [];
  const followUps = (work?.followUps || []) as HubFollowUp[];
  const showLoading = !auth.tokenReady || (loading && !work);
  const showUnauthorized = Boolean(unauthorized) && !work;
  const showError = Boolean(error) && !work && !unauthorized;

  return (
    <ModuleScaffold
      title="My Work"
      subtitle="Manny’s exception queues — overdue, waiting, decisions, and delegated work."
      showPendingBanner={false}
    >
      {actionError ? (
        <MessageBar intent="error">
          <MessageBarBody>
            <MessageBarTitle>Action did not complete</MessageBarTitle>
            {actionError}
          </MessageBarBody>
        </MessageBar>
      ) : null}

      {showLoading ? (
        <LoadingState rows={5} label={!auth.tokenReady ? 'Connecting to Hub' : 'Loading My Work'} />
      ) : null}

      {showUnauthorized ? (
        <AccessDeniedState
          title="Authenticated access required"
          description={unauthorized || 'Sign in with Microsoft to load My Work. Hub data is not shown.'}
          actions={
            <Button appearance="primary" onClick={() => void refresh()}>
              Retry
            </Button>
          }
        />
      ) : null}

      {showError ? (
        <ErrorState
          title="My Work could not load"
          description={error || 'The Hub request failed. This is not an empty work queue.'}
          actions={
            <Button appearance="primary" onClick={() => void refresh()}>
              Retry
            </Button>
          }
        />
      ) : null}

      {work ? (
        <>
          {work.suggestedNextActions?.length ? (
            <AtlasCard>
              <Text weight="semibold">{ATLAS_STATUS.needsAction}</Text>
              <ul style={{ margin: '8px 0 0', paddingLeft: 18 }}>
                {work.suggestedNextActions.map((s) => (
                  <li key={s}>
                    <Caption1>{s}</Caption1>
                  </li>
                ))}
              </ul>
            </AtlasCard>
          ) : null}
          <TabList
            selectedValue={tab}
            onTabSelect={(_, d) => setTab(d.value as Bucket)}
            style={{ flexWrap: 'wrap' }}
          >
            {buckets.map((b) => (
              <Tab key={b.id} value={b.id}>
                {b.label} ({b.count})
              </Tab>
            ))}
          </TabList>
          <AtlasCard>
            <TaskList
              tasks={list}
              bucket={tab}
              emptyTitle={`No ${BUCKET_LABEL[tab].toLowerCase()} work in this Hub queue.`}
              onComplete={(task) => void complete(task)}
            />
          </AtlasCard>
          {followUps.length ? (
            <AtlasCard title={`${ATLAS_STATUS.waiting} follow-ups`}>
              {followUps.slice(0, 20).map((f) => (
                <div key={f.id} style={{ padding: '6px 0' }}>
                  <RecordTitle to={waitingRecordPath(f)}>{f.whatIsNeeded}</RecordTitle>
                  <Caption1 style={{ display: 'block' }}>
                    {f.owedByName}
                    {f.nextFollowUpDate ? ` · next ${f.nextFollowUpDate}` : ''}
                  </Caption1>
                </div>
              ))}
            </AtlasCard>
          ) : null}
        </>
      ) : !showLoading && !showUnauthorized && !showError ? (
        <EmptyState title="My Work did not return a payload." description="Refresh after Hub is reachable." />
      ) : null}
    </ModuleScaffold>
  );
}
