import { useCallback, useEffect, useMemo, useState } from 'react';
import { AtlasCard, StatusChip, EmptyState } from '@hvcg/atlas-design-system';
import { Button, Caption1, Text, Spinner, Tab, TabList } from '@fluentui/react-components';
import { ModuleScaffold } from './shared/ModuleScaffold';
import { useMicrosoftAuth } from '../microsoft/auth/AuthProvider';
import { useAtlasRole } from '../security/RoleProvider';
import { workspaceCatalog } from '../data/workspaces';
import {
  fetchMyWork,
  patchPmTask,
  type MyWork,
  type PmTask,
} from '../integrations/hub/pmApi';
import { useHubAuth } from '../integrations/hub/useHubAuth';
import type { AtlasHubAuthHeaders } from '../integrations/hub/api';
import { QuickCaptureBar } from '../components/QuickCaptureBar';


type Bucket =
  | 'today'
  | 'overdue'
  | 'dueThisWeek'
  | 'upcoming'
  | 'waitingOnOthers'
  | 'needsOwnerDecision'
  | 'highValueOpportunities'
  | 'clientEmergencies'
  | 'autoGenerated'
  | 'delegatedToTeam'
  | 'delegatedToAgents'
  | 'requiringApproval'
  | 'recentlyCompleted';

function TaskList({
  tasks,
  onComplete,
}: {
  tasks: PmTask[];
  onComplete: (task: PmTask) => void;
}) {
  if (!tasks.length) return <EmptyState title="Nothing here" description="Clear for this view." />;
  return (
    <div>
      {tasks.map((t) => (
        <div
          key={t.id}
          style={{
            display: 'grid',
            gridTemplateColumns: '1fr auto',
            gap: 8,
            padding: '10px 0',
            borderBottom: '1px solid color-mix(in srgb, currentColor 10%, transparent)',
          }}
        >
          <div>
            <Text weight="semibold">{t.title}</Text>
            <Caption1 style={{ display: 'block' }}>
              {[t.clientName, t.priority, t.dueDate, t.assigneeName, t.source].filter(Boolean).join(' · ')}
            </Caption1>
            {t.nextAction ? <Caption1>Next: {t.nextAction}</Caption1> : null}
            {t.blocker ? <Caption1>Blocker: {t.blocker}</Caption1> : null}
          </div>
          <div style={{ display: 'flex', gap: 6 }}>
            <StatusChip
              tone={t.priority === 'critical' ? 'danger' : t.priority === 'high' ? 'warning' : 'info'}
              label={t.status}
            />
            {t.status !== 'completed' ? (
              <Button size="small" onClick={() => onComplete(t)}>
                Complete
              </Button>
            ) : null}
          </div>
        </div>
      ))}
    </div>
  );
}

export function MyWorkPage() {
  const auth = useHubAuth();
  const [work, setWork] = useState<MyWork | null>(null);
  const [tab, setTab] = useState<Bucket>('overdue');
  const [loading, setLoading] = useState(true);

  const refresh = useCallback(async () => {
    if (!auth.tokenReady) return;
    if (!auth.hasBearer) {
      setLoading(false);
      setWork(null);
      return;
    }
    setLoading(true);
    try {
      const res = await fetchMyWork(auth);
      setWork(res.myWork);
    } finally {
      setLoading(false);
    }
  }, [auth]);

  useEffect(() => {
    void refresh();
  }, [refresh]);

  if (!auth.tokenReady) {
    return (
      <ModuleScaffold title="My Work" subtitle="Preparing Microsoft session…" showPendingBanner={false}>
        <Spinner label="Acquiring Hub bearer…" />
      </ModuleScaffold>
    );
  }

  const complete = async (task: PmTask) => {
    await patchPmTask(auth, task.id, { status: 'completed', ...(task.etag ? { etag: task.etag } : {}) });
    await refresh();
  };

  const buckets: Array<{ id: Bucket; label: string; count: number }> = work
    ? [
        { id: 'overdue', label: 'Overdue', count: work.overdue.length },
        { id: 'today', label: 'Today', count: work.today.length },
        { id: 'dueThisWeek', label: 'This week', count: work.dueThisWeek.length },
        { id: 'upcoming', label: 'Upcoming', count: work.upcoming.length },
        { id: 'waitingOnOthers', label: 'Waiting', count: work.waitingOnOthers.length },
        { id: 'needsOwnerDecision', label: 'Owner decision', count: work.needsOwnerDecision.length },
        { id: 'clientEmergencies', label: 'Emergencies', count: work.clientEmergencies.length },
        { id: 'highValueOpportunities', label: 'Opportunities', count: work.highValueOpportunities.length },
        { id: 'autoGenerated', label: 'Auto', count: work.autoGenerated.length },
        { id: 'delegatedToTeam', label: 'Team', count: work.delegatedToTeam.length },
        { id: 'delegatedToAgents', label: 'Agents', count: work.delegatedToAgents.length },
        { id: 'requiringApproval', label: 'Approvals', count: work.requiringApproval.length },
        { id: 'recentlyCompleted', label: 'Done', count: work.recentlyCompleted.length },
      ]
    : [];

  const list = (work?.[tab] as PmTask[] | undefined) || [];

  return (
    <ModuleScaffold
      title="My Work"
      subtitle="Your operating queue — overdue, today, waiting, approvals, and delegated work. Identity comes from the signed-in Microsoft oid."
      showPendingBanner={false}
    >
      <QuickCaptureBar auth={auth} onCreated={() => void refresh()} />
      {work?.suggestedNextActions?.length ? (
        <AtlasCard>
          <Text weight="semibold">Suggested next actions</Text>
          <ul style={{ margin: '8px 0 0', paddingLeft: 18 }}>
            {work.suggestedNextActions.map((s) => (
              <li key={s}>
                <Caption1>{s}</Caption1>
              </li>
            ))}
          </ul>
        </AtlasCard>
      ) : null}
      {loading && !work ? (
        <Spinner label="Loading My Work…" />
      ) : (
        <>
          <TabList
            selectedValue={tab}
            onTabSelect={(_, d) => setTab(d.value as Bucket)}
            style={{ flexWrap: 'wrap' }}
          >
            {buckets.map((b) => (
              <Tab key={b.id} value={b.id}>
                {b.label} ({b.count})
              </Tab>
            ))}
          </TabList>
          <AtlasCard>
            <TaskList tasks={list} onComplete={(id) => void complete(id)} />
          </AtlasCard>
          {work?.followUps?.length ? (
            <AtlasCard title="Follow-ups / Waiting On">
              {work.followUps.slice(0, 20).map((f) => (
                <div key={f.id} style={{ padding: '6px 0' }}>
                  <Text weight="semibold">{f.whatIsNeeded}</Text>
                  <Caption1 style={{ display: 'block' }}>
                    {f.owedByName}
                    {f.nextFollowUpDate ? ` · next ${f.nextFollowUpDate}` : ''}
                  </Caption1>
                </div>
              ))}
            </AtlasCard>
          ) : null}
        </>
      )}
    </ModuleScaffold>
  );
}
