import type { KnowledgeArticle, KnowledgeUser } from './types'

const today = '2026-07-19'

function article(
  partial: Omit<KnowledgeArticle, 'history' | 'updatedAt' | 'copilotKeywords'> & {
    history?: KnowledgeArticle['history']
    keywords?: string[]
  },
): KnowledgeArticle {
  const { keywords, history, ...rest } = partial
  return {
    ...rest,
    copilotKeywords: keywords ?? [],
    updatedAt: rest.lastReviewed,
    history: history ?? [
      {
        version: rest.versionLabel,
        date: rest.lastReviewed,
        author: rest.ownerEmail,
        note: 'Catalog seed',
      },
    ],
  }
}

/** Seed corpus — mirrors docs/knowledge/INVENTORY.md */
export const KNOWLEDGE_CATALOG: KnowledgeArticle[] = [
  article({
    id: 'KA-001',
    title: 'Client Onboarding',
    knowledgeType: 'SOP',
    category: 'Onboarding',
    tags: ['onboarding', 'clients', 'sharepoint'],
    summary: 'Create client workspace, library, tasks, and kickoff for paid engagements.',
    sourceUrl: '/docs/sops/SOP_Client_Onboarding.md',
    ownerEmail: 'ops@hvcg.example',
    approvalStatus: 'Approved',
    audience: 'Internal',
    relatedModule: 'Operations',
    relatedClientCode: null,
    engagementKey: null,
    organizationId: 'HVCG',
    lastReviewed: '2026-06-01',
    nextReviewDue: '2026-08-30',
    versionLabel: '1.2',
    supersedesId: null,
    aiGroundingAllowed: true,
    usageCount: 128,
    sensitivity: 'PublicInternal',
    keywords: ['client onboarding', 'ClientStage', 'library'],
  }),
  article({
    id: 'KA-002',
    title: 'External Sharing',
    knowledgeType: 'SOP',
    category: 'Security',
    tags: ['sharing', 'security', 'guest'],
    summary: 'Approved process for sharing client or firm files outside the tenant.',
    sourceUrl: '/docs/sops/SOP_External_Sharing.md',
    ownerEmail: 'security@hvcg.example',
    approvalStatus: 'Approved',
    audience: 'Internal',
    relatedModule: 'Security',
    relatedClientCode: null,
    engagementKey: null,
    organizationId: 'HVCG',
    lastReviewed: '2026-05-15',
    nextReviewDue: '2026-08-13',
    versionLabel: '2.0',
    supersedesId: null,
    aiGroundingAllowed: true,
    usageCount: 86,
    sensitivity: 'Confidential',
    keywords: ['external sharing', 'guest access'],
  }),
  article({
    id: 'KA-003',
    title: 'Security Incident Response',
    knowledgeType: 'SOP',
    category: 'Security',
    tags: ['incident', 'security'],
    summary: 'Detect, contain, escalate, and document security incidents.',
    sourceUrl: '/docs/sops/SOP_Security_Incident_Response.md',
    ownerEmail: 'security@hvcg.example',
    approvalStatus: 'Approved',
    audience: 'Internal',
    relatedModule: 'Security',
    relatedClientCode: null,
    engagementKey: null,
    organizationId: 'HVCG',
    lastReviewed: '2026-04-20',
    nextReviewDue: '2026-07-19',
    versionLabel: '1.1',
    supersedesId: null,
    aiGroundingAllowed: true,
    usageCount: 41,
    sensitivity: 'Confidential',
  }),
  article({
    id: 'KA-004',
    title: 'Executive Escalation',
    knowledgeType: 'SOP',
    category: 'Operations',
    tags: ['escalation', 'executive'],
    summary: 'When and how to set RequiresExecutiveAttention and brief the owner.',
    sourceUrl: '/docs/sops/SOP_Executive_Escalation.md',
    ownerEmail: 'ops@hvcg.example',
    approvalStatus: 'Approved',
    audience: 'Executive',
    relatedModule: 'Executive',
    relatedClientCode: null,
    engagementKey: null,
    organizationId: 'HVCG',
    lastReviewed: '2026-06-10',
    nextReviewDue: '2026-09-08',
    versionLabel: '1.0',
    supersedesId: null,
    aiGroundingAllowed: true,
    usageCount: 55,
    sensitivity: 'Restricted',
  }),
  article({
    id: 'KA-005',
    title: 'Microsoft Copilot Readiness',
    knowledgeType: 'ProductDocumentation',
    category: 'AI',
    tags: ['copilot', 'grounding', 'sharepoint'],
    summary: 'Grounding strategy for Copilot across clients, SOPs, capital, and files.',
    sourceUrl: '/docs/architecture/COPILOT_READY.md',
    ownerEmail: 'architect@hvcg.example',
    approvalStatus: 'Approved',
    audience: 'Internal',
    relatedModule: 'AI',
    relatedClientCode: null,
    engagementKey: null,
    organizationId: 'HVCG',
    lastReviewed: '2026-07-01',
    nextReviewDue: '2026-12-28',
    versionLabel: '1.0',
    supersedesId: null,
    aiGroundingAllowed: true,
    usageCount: 72,
    sensitivity: 'PublicInternal',
    keywords: ['copilot', 'keywords', 'sensitivity labels'],
  }),
  article({
    id: 'KA-006',
    title: 'AI Governance Principles',
    knowledgeType: 'Policy',
    category: 'AI',
    tags: ['ai', 'governance', 'approval'],
    summary: 'AI drafts; humans decide. No auto external send. Auditable jobs.',
    sourceUrl: '/docs/ai/AI_GOVERNANCE.md',
    ownerEmail: 'ai-gov@hvcg.example',
    approvalStatus: 'Approved',
    audience: 'AllStaff',
    relatedModule: 'AI',
    relatedClientCode: null,
    engagementKey: null,
    organizationId: 'HVCG',
    lastReviewed: '2026-06-20',
    nextReviewDue: '2026-09-18',
    versionLabel: '1.3',
    supersedesId: null,
    aiGroundingAllowed: true,
    usageCount: 99,
    sensitivity: 'PublicInternal',
  }),
  article({
    id: 'KA-007',
    title: 'HVCG User Guide',
    knowledgeType: 'Onboarding',
    category: 'Onboarding',
    tags: ['training', 'users'],
    summary: 'Staff training guide for Command Center navigation and daily work.',
    sourceUrl: '/docs/training/USER_GUIDE.md',
    ownerEmail: 'ops@hvcg.example',
    approvalStatus: 'Approved',
    audience: 'AllStaff',
    relatedModule: 'Operations',
    relatedClientCode: null,
    engagementKey: null,
    organizationId: 'HVCG',
    lastReviewed: '2026-05-01',
    nextReviewDue: '2026-08-29',
    versionLabel: '1.0',
    supersedesId: null,
    aiGroundingAllowed: true,
    usageCount: 150,
    sensitivity: 'PublicInternal',
  }),
  article({
    id: 'KA-008',
    title: 'Where do SOPs live?',
    knowledgeType: 'FAQ',
    category: 'Operations',
    tags: ['faq', 'sop', 'knowledge'],
    summary: 'Approved SOPs are indexed in HVCG_KnowledgeArticles and filed under Knowledge/01_SOPs.',
    sourceUrl: '/docs/knowledge/INVENTORY.md',
    ownerEmail: 'knowledge@hvcg.example',
    approvalStatus: 'Approved',
    audience: 'AllStaff',
    relatedModule: 'Knowledge',
    relatedClientCode: null,
    engagementKey: null,
    organizationId: 'HVCG',
    lastReviewed: '2026-07-19',
    nextReviewDue: '2026-11-16',
    versionLabel: '1.0',
    supersedesId: null,
    aiGroundingAllowed: true,
    usageCount: 33,
    sensitivity: 'PublicInternal',
  }),
  article({
    id: 'KA-009',
    title: 'Library provisioning failed',
    knowledgeType: 'Troubleshooting',
    category: 'Troubleshooting',
    tags: ['sharepoint', 'provisioning', 'automation'],
    summary: 'If client library automation fails, notify Admin, rerun workspace scripts, log AutomationLogs.',
    sourceUrl: '/docs/sops/SOP_Client_Onboarding.md',
    ownerEmail: 'admin@hvcg.example',
    approvalStatus: 'Approved',
    audience: 'Internal',
    relatedModule: 'Deployment',
    relatedClientCode: null,
    engagementKey: null,
    organizationId: 'HVCG',
    lastReviewed: '2026-07-10',
    nextReviewDue: '2026-10-08',
    versionLabel: '1.0',
    supersedesId: null,
    aiGroundingAllowed: true,
    usageCount: 22,
    sensitivity: 'PublicInternal',
  }),
  article({
    id: 'KA-010',
    title: 'Microsoft-native architecture',
    knowledgeType: 'ArchitectureRecord',
    category: 'Architecture',
    tags: ['entra', 'dataverse', 'graph', 'azure'],
    summary: 'Atlas product architecture is Microsoft-native only — Entra, Dataverse, SharePoint, Graph, Azure.',
    sourceUrl: '/docs/architecture/COPILOT_READY.md',
    ownerEmail: 'architect@hvcg.example',
    approvalStatus: 'Approved',
    audience: 'Internal',
    relatedModule: 'Deployment',
    relatedClientCode: null,
    engagementKey: null,
    organizationId: 'HVCG',
    lastReviewed: '2026-07-15',
    nextReviewDue: '2027-01-11',
    versionLabel: '1.0',
    supersedesId: null,
    aiGroundingAllowed: true,
    usageCount: 60,
    sensitivity: 'PublicInternal',
  }),
  article({
    id: 'KA-011',
    title: 'Capital package folder practice',
    knowledgeType: 'CapitalAdvisoryGuidance',
    category: 'Capital',
    tags: ['capital', 'lender', 'investor'],
    summary: 'Keep capital packages in client library folders 16/17 with status and amount in titles where practical.',
    sourceUrl: '/docs/architecture/COPILOT_READY.md',
    ownerEmail: 'capital@hvcg.example',
    approvalStatus: 'Approved',
    audience: 'Capital',
    relatedModule: 'Capital',
    relatedClientCode: null,
    engagementKey: null,
    organizationId: 'HVCG',
    lastReviewed: '2026-06-25',
    nextReviewDue: '2026-09-23',
    versionLabel: '1.0',
    supersedesId: null,
    aiGroundingAllowed: true,
    usageCount: 47,
    sensitivity: 'Confidential',
  }),
  article({
    id: 'KA-012',
    title: 'Finance field sensitivity',
    knowledgeType: 'FinanceGuidance',
    category: 'Finance',
    tags: ['finance', 'permissions', 'kpi'],
    summary: 'Hide retainer, invoice, and success-fee fields unless Owner/Admin/OpsMgr finance viewer.',
    sourceUrl: '/PERMISSIONS_MATRIX.md',
    ownerEmail: 'finance@hvcg.example',
    approvalStatus: 'Approved',
    audience: 'Finance',
    relatedModule: 'Finance',
    relatedClientCode: null,
    engagementKey: null,
    organizationId: 'HVCG',
    lastReviewed: '2026-07-05',
    nextReviewDue: '2026-10-03',
    versionLabel: '1.0',
    supersedesId: null,
    aiGroundingAllowed: true,
    usageCount: 38,
    sensitivity: 'Restricted',
  }),
  article({
    id: 'KA-013',
    title: 'Client library folder taxonomy 00–23',
    knowledgeType: 'Template',
    category: 'Delivery',
    tags: ['taxonomy', 'folders', 'client-library'],
    summary: 'Standard client document library folders from engagement through closed/archived.',
    sourceUrl: '/src/sharepoint/libraries/HVCG_ClientLibrary.template.json',
    ownerEmail: 'ops@hvcg.example',
    approvalStatus: 'Approved',
    audience: 'Internal',
    relatedModule: 'ClientPortal',
    relatedClientCode: null,
    engagementKey: null,
    organizationId: 'HVCG',
    lastReviewed: '2026-07-12',
    nextReviewDue: '2026-10-10',
    versionLabel: '2.3',
    supersedesId: null,
    aiGroundingAllowed: true,
    usageCount: 110,
    sensitivity: 'PublicInternal',
  }),
  article({
    id: 'KA-014',
    title: 'Knowledge Platform v1',
    knowledgeType: 'ReleaseDocumentation',
    category: 'Release',
    tags: ['release', 'knowledge'],
    summary: 'Product release notes for searchable, role-aware Knowledge Platform v1.',
    sourceUrl: '/docs/knowledge/README.md',
    ownerEmail: 'knowledge@hvcg.example',
    approvalStatus: 'Approved',
    audience: 'AllStaff',
    relatedModule: 'Knowledge',
    relatedClientCode: null,
    engagementKey: null,
    organizationId: 'HVCG',
    lastReviewed: '2026-07-19',
    nextReviewDue: '2026-10-17',
    versionLabel: '0.1.0',
    supersedesId: null,
    aiGroundingAllowed: true,
    usageCount: 12,
    sensitivity: 'PublicInternal',
  }),
  article({
    id: 'KA-015',
    title: 'Knowledge SoR decision',
    knowledgeType: 'Decision',
    category: 'Architecture',
    tags: ['decision', 'sor', 'sharepoint'],
    summary: 'HVCG_KnowledgeArticles is the single catalog SoR; files live in the Knowledge library.',
    sourceUrl: '/docs/knowledge/INVENTORY.md',
    ownerEmail: 'knowledge@hvcg.example',
    approvalStatus: 'Approved',
    audience: 'Internal',
    relatedModule: 'Knowledge',
    relatedClientCode: null,
    engagementKey: null,
    organizationId: 'HVCG',
    lastReviewed: '2026-07-19',
    nextReviewDue: '2027-01-15',
    versionLabel: '1.0',
    supersedesId: null,
    aiGroundingAllowed: true,
    usageCount: 18,
    sensitivity: 'PublicInternal',
  }),
  article({
    id: 'KA-016',
    title: 'CCB engagement working notes',
    knowledgeType: 'ClientKnowledge',
    category: 'Client',
    tags: ['ccb', 'engagement'],
    summary: 'Client-confidential working notes for Colorado Craft Beef — not globally searchable.',
    sourceUrl: '/clients/CCB/notes',
    ownerEmail: 'pm@hvcg.example',
    approvalStatus: 'Approved',
    audience: 'ClientScoped',
    relatedModule: 'ClientPortal',
    relatedClientCode: 'CCB',
    engagementKey: 'CCB-2026-01',
    organizationId: 'HVCG',
    lastReviewed: '2026-07-18',
    nextReviewDue: '2026-10-16',
    versionLabel: '1.0',
    supersedesId: null,
    aiGroundingAllowed: false,
    usageCount: 9,
    sensitivity: 'ClientConfidential',
  }),
  article({
    id: 'KA-017',
    title: 'Kickoff meeting notes template',
    knowledgeType: 'MeetingNote',
    category: 'Operations',
    tags: ['meeting', 'template', 'draft'],
    summary: 'Draft meeting-note pattern pending Ops approval.',
    sourceUrl: '/docs/knowledge/METADATA_MODEL.md',
    ownerEmail: 'ops@hvcg.example',
    approvalStatus: 'Draft',
    audience: 'Internal',
    relatedModule: 'Operations',
    relatedClientCode: null,
    engagementKey: null,
    organizationId: 'HVCG',
    lastReviewed: '2026-07-17',
    nextReviewDue: '2026-08-16',
    versionLabel: '0.1',
    supersedesId: null,
    aiGroundingAllowed: false,
    usageCount: 2,
    sensitivity: 'PublicInternal',
  }),
  article({
    id: 'KA-018',
    title: 'Diligence checklist map',
    knowledgeType: 'EngagementKnowledge',
    category: 'Delivery',
    tags: ['diligence', 'checklist'],
    summary: 'Engagement diligence checklist mapping — awaiting approval.',
    sourceUrl: '/docs/knowledge/TAXONOMY.md',
    ownerEmail: 'pm@hvcg.example',
    approvalStatus: 'InReview',
    audience: 'Internal',
    relatedModule: 'CRM',
    relatedClientCode: null,
    engagementKey: null,
    organizationId: 'HVCG',
    lastReviewed: '2026-07-16',
    nextReviewDue: '2026-08-15',
    versionLabel: '0.9',
    supersedesId: null,
    aiGroundingAllowed: false,
    usageCount: 4,
    sensitivity: 'Confidential',
  }),
  article({
    id: 'KA-019',
    title: 'External sharing policy (stale demo)',
    knowledgeType: 'Policy',
    category: 'Security',
    tags: ['policy', 'sharing', 'stale'],
    summary: 'Approved policy past NextReviewDue — demonstrates stale-content alerts.',
    sourceUrl: '/docs/sops/SOP_External_Sharing.md',
    ownerEmail: 'security@hvcg.example',
    approvalStatus: 'Approved',
    audience: 'Internal',
    relatedModule: 'Security',
    relatedClientCode: null,
    engagementKey: null,
    organizationId: 'HVCG',
    lastReviewed: '2025-12-01',
    nextReviewDue: '2026-03-01',
    versionLabel: '1.0',
    supersedesId: null,
    aiGroundingAllowed: true,
    usageCount: 15,
    sensitivity: 'Confidential',
  }),
  article({
    id: 'KA-020',
    title: 'Duplicate USER_GUIDE paths — do not republish',
    knowledgeType: 'KnowledgeArticle',
    category: 'Admin',
    tags: ['archive', 'duplicate'],
    summary: 'Archived conflict record: prefer docs/training/USER_GUIDE.md as canonical.',
    sourceUrl: '/docs/knowledge/ARCHIVE.md',
    ownerEmail: 'knowledge@hvcg.example',
    approvalStatus: 'Archived',
    audience: 'Internal',
    relatedModule: 'Knowledge',
    relatedClientCode: null,
    engagementKey: null,
    organizationId: 'HVCG',
    lastReviewed: '2026-07-19',
    nextReviewDue: '2027-07-19',
    versionLabel: '1.0',
    supersedesId: null,
    aiGroundingAllowed: false,
    usageCount: 0,
    sensitivity: 'PublicInternal',
  }),
]

export const DEMO_USERS: KnowledgeUser[] = [
  {
    id: 'u-owner',
    name: 'Manny Owner',
    email: 'owner@hvcg.example',
    role: 'Owner',
    assignedClients: ['CCB', 'ACME'],
    organizationId: 'HVCG',
  },
  {
    id: 'u-ops',
    name: 'Ops Manager',
    email: 'ops@hvcg.example',
    role: 'OpsManager',
    assignedClients: ['CCB', 'ACME'],
    organizationId: 'HVCG',
  },
  {
    id: 'u-pm',
    name: 'Project Manager',
    email: 'pm@hvcg.example',
    role: 'ProjectManager',
    assignedClients: ['CCB'],
    organizationId: 'HVCG',
  },
  {
    id: 'u-capital',
    name: 'Capital Advisor',
    email: 'capital@hvcg.example',
    role: 'CapitalAdvisor',
    assignedClients: ['CCB'],
    organizationId: 'HVCG',
  },
  {
    id: 'u-finance',
    name: 'Financial Analyst',
    email: 'finance@hvcg.example',
    role: 'FinancialAnalyst',
    assignedClients: ['ACME'],
    organizationId: 'HVCG',
  },
  {
    id: 'u-contractor',
    name: 'Contractor',
    email: 'contractor@hvcg.example',
    role: 'Contractor',
    assignedClients: ['CCB'],
    organizationId: 'HVCG',
  },
  {
    id: 'u-readonly',
    name: 'Read Only',
    email: 'readonly@hvcg.example',
    role: 'ReadOnly',
    assignedClients: [],
    organizationId: 'HVCG',
  },
  {
    id: 'u-client',
    name: 'Client Contact',
    email: 'client@ccb.example',
    role: 'ClientContact',
    assignedClients: ['CCB'],
    organizationId: 'HVCG',
  },
]

export const HVCG_ORG_ID = 'HVCG'

export const REFERENCE_TODAY = today
