import type { ProductState } from './types'

const now = '2026-07-20T18:00:00.000Z'

export const productSeed: ProductState = {
  currentUser: 'Manny Barela',
  projects: [
    {
      id: 'p-1',
      name: 'Operations Hub Command Center',
      client: 'HVCG Internal',
      owner: 'Manny Barela',
      status: 'In Progress',
      health: 'Green',
      priority: 'Critical',
      percentComplete: 62,
      startDate: '2026-07-10',
      dueDate: '2026-07-25',
      nextAction: 'Ship portfolio + approval workflows for QA',
      tags: ['internal', 'ops'],
      archived: false,
      updatedAt: now,
      summary: 'Operational command center for projects, tasks, approvals, and escalations.',
    },
    {
      id: 'p-2',
      name: 'Summit Infrastructure delivery',
      client: 'Summit Infrastructure',
      owner: 'Alex Rivera',
      status: 'At Risk',
      health: 'Yellow',
      priority: 'High',
      percentComplete: 48,
      startDate: '2026-06-01',
      dueDate: '2026-07-22',
      nextAction: 'Unblock valuation inputs from client',
      tags: ['client', 'delivery'],
      archived: false,
      updatedAt: '2026-07-19T16:00:00.000Z',
      summary: 'Client engagement delivery with funding package milestones.',
    },
    {
      id: 'p-3',
      name: 'Cobalt scope change',
      client: 'Cobalt Holdings',
      owner: 'Jordan Lee',
      status: 'Blocked',
      health: 'Red',
      priority: 'High',
      percentComplete: 35,
      startDate: '2026-05-15',
      dueDate: '2026-07-18',
      nextAction: 'Owner decision on commercial exception',
      tags: ['client', 'commercial'],
      archived: false,
      updatedAt: '2026-07-18T12:00:00.000Z',
      summary: 'Scope change awaiting commercial approval.',
    },
    {
      id: 'p-4',
      name: 'Weekly ops cadence',
      owner: 'Casey Nguyen',
      status: 'On Track',
      health: 'Green',
      priority: 'Medium',
      percentComplete: 80,
      startDate: '2026-07-01',
      dueDate: '2026-09-30',
      nextAction: 'Publish Monday status digest',
      tags: ['recurring', 'internal'],
      archived: false,
      updatedAt: '2026-07-20T10:00:00.000Z',
      summary: 'Recurring internal operating rhythm.',
    },
    {
      id: 'p-5',
      name: 'RC-1 documentation archive',
      owner: 'Casey Nguyen',
      status: 'Completed',
      health: 'Green',
      priority: 'Low',
      percentComplete: 100,
      startDate: '2026-06-20',
      dueDate: '2026-07-16',
      nextAction: 'None — complete',
      tags: ['docs'],
      archived: false,
      updatedAt: '2026-07-16T20:00:00.000Z',
      summary: 'Closed documentation package for RC-1.',
    },
    {
      id: 'p-6',
      name: 'Legacy portal migration notes',
      owner: 'Sam Okonkwo',
      status: 'Archived',
      health: 'Green',
      priority: 'Low',
      percentComplete: 100,
      startDate: '2026-04-01',
      dueDate: '2026-05-01',
      nextAction: 'Archived',
      tags: ['archive'],
      archived: true,
      updatedAt: '2026-05-02T00:00:00.000Z',
      summary: 'Historical notes — archived.',
    },
  ],
  milestones: [
    { id: 'm-1', projectId: 'p-1', title: 'Portfolio MVP', dueDate: '2026-07-21', status: 'In Progress', owner: 'Manny Barela', percentComplete: 70 },
    { id: 'm-2', projectId: 'p-1', title: 'Approval workflow QA', dueDate: '2026-07-24', status: 'Not Started', owner: 'Riley Chen', percentComplete: 0 },
    { id: 'm-3', projectId: 'p-2', title: 'Funding package draft', dueDate: '2026-07-20', status: 'At Risk', owner: 'Alex Rivera', percentComplete: 55 },
    { id: 'm-4', projectId: 'p-3', title: 'Commercial exception decision', dueDate: '2026-07-18', status: 'Blocked', owner: 'Manny Barela', percentComplete: 10 },
    { id: 'm-5', projectId: 'p-4', title: 'Q3 cadence lock', dueDate: '2026-07-31', status: 'On Track', owner: 'Casey Nguyen', percentComplete: 40 },
  ],
  tasks: [
    {
      id: 't-1',
      projectId: 'p-1',
      milestoneId: 'm-1',
      title: 'Implement portfolio views',
      description: 'Executive, My Work, At Risk, Blocked, Overdue, Approvals.',
      status: 'In Progress',
      priority: 'Critical',
      assignee: 'Manny Barela',
      dueDate: '2026-07-20',
      dependsOn: [],
      nextAction: 'Finish filtered views + project detail',
      updatedAt: now,
    },
    {
      id: 't-2',
      projectId: 'p-1',
      milestoneId: 'm-2',
      title: 'Wire approval approve/reject actions',
      description: 'Role-aware approval decisions with activity history.',
      status: 'Awaiting Approval',
      priority: 'High',
      assignee: 'Alex Rivera',
      dueDate: '2026-07-21',
      dependsOn: ['t-1'],
      nextAction: 'Owner review of approval UX',
      updatedAt: now,
    },
    {
      id: 't-3',
      projectId: 'p-2',
      milestoneId: 'm-3',
      title: 'Collect valuation inputs',
      description: 'Client document chase for Summit package.',
      status: 'Blocked',
      priority: 'High',
      assignee: 'Alex Rivera',
      dueDate: '2026-07-19',
      dependsOn: [],
      nextAction: 'Escalate overdue client docs',
      updatedAt: '2026-07-19T16:00:00.000Z',
    },
    {
      id: 't-4',
      projectId: 'p-3',
      milestoneId: 'm-4',
      title: 'Draft commercial exception brief',
      description: 'Prepare owner decision packet.',
      status: 'At Risk',
      priority: 'Critical',
      assignee: 'Jordan Lee',
      dueDate: '2026-07-18',
      dependsOn: [],
      nextAction: 'Submit for owner approval',
      updatedAt: '2026-07-18T12:00:00.000Z',
    },
    {
      id: 't-5',
      projectId: 'p-4',
      milestoneId: 'm-5',
      title: 'Publish weekly ops digest',
      description: 'Recurring Monday digest to leadership.',
      status: 'On Track',
      priority: 'Medium',
      assignee: 'Casey Nguyen',
      dueDate: '2026-07-21',
      dependsOn: [],
      recurring: true,
      recurrence: 'Weekly · Monday',
      nextAction: 'Assemble digest content',
      updatedAt: '2026-07-20T10:00:00.000Z',
    },
    {
      id: 't-6',
      projectId: 'p-2',
      title: 'Internal QA of package',
      description: 'Depends on valuation inputs.',
      status: 'Not Started',
      priority: 'Medium',
      assignee: 'Riley Chen',
      dueDate: '2026-07-23',
      dependsOn: ['t-3'],
      nextAction: 'Wait on t-3',
      updatedAt: '2026-07-17T09:00:00.000Z',
    },
    {
      id: 't-7',
      projectId: 'p-5',
      title: 'Archive RC-1 package',
      description: 'Completed archival task.',
      status: 'Completed',
      priority: 'Low',
      assignee: 'Casey Nguyen',
      dueDate: '2026-07-16',
      dependsOn: [],
      nextAction: 'Done',
      updatedAt: '2026-07-16T20:00:00.000Z',
    },
  ],
  approvals: [
    {
      id: 'a-1',
      projectId: 'p-1',
      taskId: 't-2',
      title: 'Approve Ops Hub approval UX',
      requester: 'Alex Rivera',
      approver: 'Manny Barela',
      status: 'Pending',
      requestedAt: '2026-07-20T14:00:00.000Z',
    },
    {
      id: 'a-2',
      projectId: 'p-3',
      title: 'Commercial exception — Cobalt',
      requester: 'Jordan Lee',
      approver: 'Manny Barela',
      status: 'Pending',
      requestedAt: '2026-07-18T15:00:00.000Z',
      note: 'Fee impact requires owner.',
    },
    {
      id: 'a-3',
      projectId: 'p-5',
      title: 'RC-1 archive release',
      requester: 'Casey Nguyen',
      approver: 'Manny Barela',
      status: 'Approved',
      requestedAt: '2026-07-16T10:00:00.000Z',
      decidedAt: '2026-07-16T18:00:00.000Z',
    },
  ],
  risks: [
    {
      id: 'r-1',
      projectId: 'p-2',
      title: 'Client input delay may slip close',
      severity: 'High',
      owner: 'Alex Rivera',
      status: 'At Risk',
      mitigation: 'Daily chase + escalation',
      dueDate: '2026-07-21',
    },
    {
      id: 'r-2',
      projectId: 'p-3',
      title: 'Commercial exception unresolved',
      severity: 'Critical',
      owner: 'Jordan Lee',
      status: 'Blocked',
      mitigation: 'Owner decision gate',
      dueDate: '2026-07-18',
    },
  ],
  issues: [
    {
      id: 'i-1',
      projectId: 'p-2',
      title: 'Missing valuation workbook',
      severity: 'High',
      owner: 'Alex Rivera',
      status: 'Blocked',
      blocker: true,
    },
    {
      id: 'i-2',
      projectId: 'p-1',
      title: 'Mobile nav overflow for 20 modules',
      severity: 'Medium',
      owner: 'Manny Barela',
      status: 'In Progress',
      blocker: false,
    },
  ],
  decisions: [
    {
      id: 'd-1',
      projectId: 'p-1',
      title: 'Single task system',
      decision: 'Ops Hub uses one product task model; no parallel todo system.',
      owner: 'Manny Barela',
      at: '2026-07-19T12:00:00.000Z',
      status: 'Completed',
    },
  ],
  comments: [
    {
      id: 'c-1',
      projectId: 'p-2',
      entityType: 'task',
      entityId: 't-3',
      author: 'Alex Rivera',
      body: 'Client confirmed they will upload by EOD tomorrow.',
      at: '2026-07-19T17:00:00.000Z',
    },
  ],
  documents: [
    {
      id: 'doc-1',
      projectId: 'p-3',
      entityType: 'approval',
      entityId: 'a-2',
      name: 'Cobalt-exception-brief.pdf',
      kind: 'PDF',
      attachedBy: 'Jordan Lee',
      at: '2026-07-18T15:05:00.000Z',
    },
  ],
  activity: [
    {
      id: 'act-1',
      entityType: 'project',
      entityId: 'p-1',
      projectId: 'p-1',
      actor: 'Manny Barela',
      action: 'updated',
      detail: 'Advanced portfolio MVP to 62%',
      at: now,
    },
    {
      id: 'act-2',
      entityType: 'approval',
      entityId: 'a-2',
      projectId: 'p-3',
      actor: 'Jordan Lee',
      action: 'requested approval',
      detail: 'Commercial exception submitted',
      at: '2026-07-18T15:00:00.000Z',
    },
    {
      id: 'act-3',
      entityType: 'issue',
      entityId: 'i-1',
      projectId: 'p-2',
      actor: 'Alex Rivera',
      action: 'logged blocker',
      detail: 'Missing valuation workbook',
      at: '2026-07-19T16:00:00.000Z',
    },
  ],
}
