import type { ProjectTemplateRecord, TeamMemberRecord } from './types.ts';

export const DEFAULT_TEAM: TeamMemberRecord[] = [
  {
    id: 'person-manny',
    name: 'Manny Barela',
    email: 'manuel@highvaluecapitalgroup.com',
    role: 'Owner / CEO',
    kind: 'person',
    active: true,
    capacityHoursPerWeek: 50,
  },
  {
    id: 'person-stephen',
    name: 'Stephen',
    role: 'Team',
    kind: 'person',
    active: true,
    capacityHoursPerWeek: 40,
  },
  {
    id: 'person-john',
    name: 'John',
    role: 'Team',
    kind: 'person',
    active: true,
    capacityHoursPerWeek: 40,
  },
  {
    id: 'person-mason',
    name: 'Mason',
    role: 'Team',
    kind: 'person',
    active: true,
    capacityHoursPerWeek: 40,
  },
  {
    id: 'agent-atlas',
    name: 'Atlas OS Agent',
    role: 'Operating System Agent',
    kind: 'agent',
    active: true,
  },
  {
    id: 'agent-client360',
    name: 'Client 360 Ingestion Agent',
    role: 'Data Agent',
    kind: 'agent',
    active: true,
  },
  {
    id: 'agent-work-extractor',
    name: 'Work Extraction Agent',
    role: 'Automation Agent',
    kind: 'agent',
    active: true,
  },
];

export const PROJECT_TEMPLATES: ProjectTemplateRecord[] = [
  {
    id: 'tmpl-client-onboarding',
    name: 'New client onboarding',
    projectType: 'client_onboarding',
    phases: ['Kickoff', 'Document collection', 'Setup', 'First deliverable'],
    milestones: [
      { title: 'Engagement letter signed', offsetDays: 0 },
      { title: 'Documents collected', offsetDays: 7 },
      { title: 'Workspace ready', offsetDays: 10 },
      { title: 'First deliverable', offsetDays: 21 },
    ],
    tasks: [
      { title: 'Send engagement letter / agreement', priority: 'high', offsetDays: 0 },
      { title: 'Collect KYC / identity documents', priority: 'high', offsetDays: 1 },
      { title: 'Collect financial statements', priority: 'high', offsetDays: 2 },
      { title: 'Create Client 360 workspace', priority: 'normal', offsetDays: 1 },
      { title: 'Schedule kickoff meeting', priority: 'normal', offsetDays: 0 },
      { title: 'Confirm success criteria with client', priority: 'high', offsetDays: 3 },
    ],
    requiredDocuments: ['Agreement', 'Bank statements', 'Tax returns', 'Entity docs'],
    defaultOwnerRole: 'Owner / CEO',
    deliverables: ['Onboarding summary', 'Client workspace'],
    approvalGates: ['Agreement signed', 'Owner kickoff complete'],
  },
  {
    id: 'tmpl-capital-advisory',
    name: 'Capital advisory engagement',
    projectType: 'capital_advisory',
    phases: ['Discovery', 'Package', 'Lender outreach', 'Closing'],
    milestones: [
      { title: 'Intake complete', offsetDays: 5 },
      { title: 'Funding package ready', offsetDays: 20 },
      { title: 'Lender intros sent', offsetDays: 30 },
      { title: 'Term sheet / commitment', offsetDays: 60 },
    ],
    tasks: [
      { title: 'Complete funding readiness review', priority: 'high', offsetDays: 2 },
      { title: 'Build sources & uses', priority: 'high', offsetDays: 7 },
      { title: 'Prepare lender memo', priority: 'high', offsetDays: 14 },
      { title: 'Identify target lenders', priority: 'normal', offsetDays: 10 },
    ],
    requiredDocuments: ['Financials', 'Business plan', 'Collateral schedule', 'Use of proceeds'],
    deliverables: ['Lender package', 'Target lender list'],
    approvalGates: ['Package quality review'],
  },
  {
    id: 'tmpl-sba-package',
    name: 'SBA loan package',
    projectType: 'funding_request',
    phases: ['Eligibility', 'Document assembly', 'Submission', 'Underwriting support'],
    milestones: [
      { title: 'Eligibility confirmed', offsetDays: 3 },
      { title: 'Package complete', offsetDays: 21 },
      { title: 'Submitted to lender', offsetDays: 28 },
    ],
    tasks: [
      { title: 'Confirm SBA product fit', priority: 'critical', offsetDays: 1 },
      { title: 'Collect personal financial statement', priority: 'high', offsetDays: 5 },
      { title: 'Collect business tax returns', priority: 'high', offsetDays: 5 },
      { title: 'Draft Form 1919 / application materials', priority: 'high', offsetDays: 10 },
    ],
    requiredDocuments: ['Tax returns', 'PFS', 'Debt schedule', 'Business plan'],
    deliverables: ['SBA package'],
    approvalGates: ['Owner package sign-off'],
  },
  {
    id: 'tmpl-fractional-cfo',
    name: 'Fractional CFO engagement',
    projectType: 'fractional_cfo',
    phases: ['Diagnostics', 'Cadence setup', 'Reporting', 'Advisory'],
    milestones: [
      { title: 'Financial baseline', offsetDays: 14 },
      { title: 'Reporting cadence live', offsetDays: 30 },
    ],
    tasks: [
      { title: 'Map chart of accounts / systems', priority: 'high', offsetDays: 3 },
      { title: 'Build cash-flow forecast', priority: 'critical', offsetDays: 10 },
      { title: 'Establish weekly finance huddle', priority: 'normal', offsetDays: 7 },
    ],
    requiredDocuments: ['Bank feeds', 'P&L', 'Balance sheet', 'AP/AR aging'],
    deliverables: ['Cash-flow forecast', 'Monthly CFO pack'],
    approvalGates: ['Forecast assumptions approved'],
  },
  {
    id: 'tmpl-ai-assessment',
    name: 'AI assessment',
    projectType: 'ai_implementation',
    phases: ['Discovery', 'Opportunity map', 'Roadmap', 'Pilot proposal'],
    milestones: [
      { title: 'Discovery complete', offsetDays: 10 },
      { title: 'Roadmap delivered', offsetDays: 21 },
    ],
    tasks: [
      { title: 'Stakeholder interviews', priority: 'high', offsetDays: 3 },
      { title: 'Current-state process map', priority: 'high', offsetDays: 7 },
      { title: 'Prioritize automation opportunities', priority: 'normal', offsetDays: 14 },
    ],
    requiredDocuments: ['Org chart', 'Process docs', 'Tool inventory'],
    deliverables: ['AI opportunity assessment', 'Pilot proposal'],
    approvalGates: ['Roadmap owner approval'],
  },
  {
    id: 'tmpl-ai-implementation',
    name: 'AI implementation',
    projectType: 'ai_implementation',
    phases: ['Design', 'Build', 'Pilot', 'Rollout'],
    milestones: [
      { title: 'Pilot live', offsetDays: 30 },
      { title: 'Production rollout', offsetDays: 60 },
    ],
    tasks: [
      { title: 'Define success metrics', priority: 'high', offsetDays: 2 },
      { title: 'Build pilot workflow', priority: 'critical', offsetDays: 14 },
      { title: 'Train users', priority: 'normal', offsetDays: 28 },
    ],
    requiredDocuments: ['Data access list', 'Security requirements'],
    deliverables: ['Working pilot', 'Runbook'],
    approvalGates: ['Security review', 'Go-live approval'],
  },
  {
    id: 'tmpl-website',
    name: 'Website build',
    projectType: 'website',
    phases: ['Brief', 'Design', 'Build', 'Launch'],
    milestones: [
      { title: 'Design approved', offsetDays: 14 },
      { title: 'Launch', offsetDays: 45 },
    ],
    tasks: [
      { title: 'Collect brand assets', priority: 'high', offsetDays: 2 },
      { title: 'Draft site map + copy', priority: 'high', offsetDays: 7 },
      { title: 'Build pages', priority: 'normal', offsetDays: 21 },
      { title: 'QA + launch checklist', priority: 'high', offsetDays: 40 },
    ],
    requiredDocuments: ['Brand guidelines', 'Domain access'],
    deliverables: ['Live website'],
    approvalGates: ['Design approval', 'Launch approval'],
  },
  {
    id: 'tmpl-document-collection',
    name: 'Document collection',
    projectType: 'client_engagement',
    phases: ['Request', 'Chase', 'Validate', 'Archive'],
    milestones: [{ title: 'All required docs received', offsetDays: 14 }],
    tasks: [
      { title: 'Send document checklist', priority: 'high', offsetDays: 0 },
      { title: 'Follow up on missing documents', priority: 'high', offsetDays: 3 },
      { title: 'Validate and file documents', priority: 'normal', offsetDays: 10 },
    ],
    requiredDocuments: [],
    deliverables: ['Complete document set'],
    approvalGates: [],
  },
  {
    id: 'tmpl-internal-software',
    name: 'Internal software development',
    projectType: 'product_development',
    phases: ['Scope', 'Build', 'QA', 'Release'],
    milestones: [
      { title: 'MVP scope locked', offsetDays: 7 },
      { title: 'MVP released', offsetDays: 30 },
    ],
    tasks: [
      { title: 'Write requirements / acceptance criteria', priority: 'high', offsetDays: 2 },
      { title: 'Implement core flows', priority: 'critical', offsetDays: 14 },
      { title: 'QA + regression', priority: 'high', offsetDays: 25 },
    ],
    requiredDocuments: ['Requirements'],
    deliverables: ['Shipped release'],
    approvalGates: ['Owner acceptance'],
  },
  {
    id: 'tmpl-marketing-campaign',
    name: 'Marketing campaign',
    projectType: 'marketing',
    phases: ['Brief', 'Create', 'Launch', 'Measure'],
    milestones: [
      { title: 'Assets ready', offsetDays: 14 },
      { title: 'Campaign live', offsetDays: 21 },
    ],
    tasks: [
      { title: 'Define ICP + offer', priority: 'high', offsetDays: 2 },
      { title: 'Create campaign assets', priority: 'normal', offsetDays: 10 },
      { title: 'Launch + track KPIs', priority: 'high', offsetDays: 21 },
    ],
    requiredDocuments: ['Brand assets'],
    deliverables: ['Campaign live'],
    approvalGates: ['Creative approval'],
  },
];
