/**
 * Project Atlas operating-system / PM data model.
 * Atlas is SoT for projects, tasks, commitments, decisions, and work ownership.
 * Source systems remain authoritative for emails, docs, accounting, contracts.
 */

export type BusinessEntityId = 'HVCG' | 'HVS' | 'legacy' | 'personal_business' | 'unknown' | string;

export type ProjectType =
  | 'client_engagement'
  | 'capital_advisory'
  | 'funding_request'
  | 'fractional_cfo'
  | 'ai_implementation'
  | 'internal_operations'
  | 'product_development'
  | 'marketing'
  | 'sales'
  | 'legal_compliance'
  | 'client_onboarding'
  | 'website'
  | 'technology'
  | 'finance'
  | 'hiring'
  | 'personal_owner_task'
  | 'strategic_initiative';

export type ProjectStatus =
  | 'draft'
  | 'active'
  | 'on_hold'
  | 'blocked'
  | 'completed'
  | 'cancelled'
  | 'archived';

export type ProjectHealth = 'healthy' | 'watch' | 'at_risk' | 'critical' | 'unknown';

export type TaskStatus =
  | 'inbox'
  | 'ready'
  | 'in_progress'
  | 'waiting'
  | 'blocked'
  | 'needs_review'
  | 'needs_owner_approval'
  | 'scheduled'
  | 'completed'
  | 'cancelled'
  | 'deferred';

export type TaskPriority = 'critical' | 'high' | 'normal' | 'low' | 'someday';

export type WorkAssigneeKind = 'person' | 'agent' | 'unassigned';

export type InboxClassification =
  | 'task'
  | 'project'
  | 'client_update'
  | 'document'
  | 'communication'
  | 'decision'
  | 'opportunity'
  | 'risk'
  | 'waiting_item'
  | 'reference'
  | 'duplicate'
  | 'no_action';

export type RiskSeverity = 'critical' | 'high' | 'medium' | 'low';

export interface SourceLink {
  provider?: string;
  connectionId?: string;
  sourceRecordId?: string;
  sourceUrl?: string;
  kind?: string;
  title?: string;
}

export interface ActivityEvent {
  id: string;
  at: string;
  actor: string;
  action: string;
  detail?: string;
}

export interface ChecklistItem {
  id: string;
  text: string;
  done: boolean;
}

export interface MilestoneRecord {
  id: string;
  projectId: string;
  title: string;
  dueDate?: string;
  status: 'pending' | 'in_progress' | 'completed' | 'missed';
  completedAt?: string;
  order: number;
}

export interface ProjectRecord {
  id: string;
  name: string;
  clientId?: string;
  clientName?: string;
  businessEntity: BusinessEntityId;
  projectType: ProjectType;
  description?: string;
  objective?: string;
  successCriteria?: string;
  ownerId: string;
  ownerName: string;
  teamMemberIds: string[];
  startDate?: string;
  targetCompletionDate?: string;
  currentPhase?: string;
  status: ProjectStatus;
  priority: TaskPriority;
  health: ProjectHealth;
  progressPercent: number;
  budget?: number;
  revenue?: number;
  expenses?: number;
  nextAction?: string;
  templateId?: string;
  sourceLinks: SourceLink[];
  tags: string[];
  createdAt: string;
  updatedAt: string;
  lastActivityAt?: string;
  archivedAt?: string;
}

export interface TaskRecord {
  id: string;
  title: string;
  description?: string;
  projectId?: string;
  clientId?: string;
  clientName?: string;
  engagementId?: string;
  assigneeKind: WorkAssigneeKind;
  assigneeId?: string;
  assigneeName?: string;
  creatorId: string;
  creatorName: string;
  source: string;
  sourceLinks: SourceLink[];
  status: TaskStatus;
  priority: TaskPriority;
  startDate?: string;
  dueDate?: string;
  estimatedMinutes?: number;
  actualMinutes?: number;
  dependencyTaskIds: string[];
  blocker?: string;
  requiresApproval: boolean;
  recurrence?: string;
  checklist: ChecklistItem[];
  revenueImpact?: string;
  riskImpact?: string;
  escalationStatus?: string;
  nextAction?: string;
  completionEvidence?: string;
  confidence: number;
  autoGenerated: boolean;
  businessEntity?: BusinessEntityId;
  createdAt: string;
  updatedAt: string;
  completedAt?: string;
  activity: ActivityEvent[];
}

export interface DecisionRecord {
  id: string;
  title: string;
  decision: string;
  date: string;
  ownerId: string;
  ownerName: string;
  context?: string;
  optionsConsidered?: string[];
  finalChoice?: string;
  reason?: string;
  clientId?: string;
  clientName?: string;
  projectId?: string;
  sourceLinks: SourceLink[];
  impact?: string;
  followUpAction?: string;
  reviewDate?: string;
  status: 'open' | 'decided' | 'deferred';
  createdAt: string;
  updatedAt: string;
}

export interface CommitmentRecord {
  id: string;
  description: string;
  madeById: string;
  madeByName: string;
  madeToId?: string;
  madeToName: string;
  dateMade: string;
  dueDate?: string;
  clientId?: string;
  clientName?: string;
  projectId?: string;
  sourceLinks: SourceLink[];
  status: 'open' | 'completed' | 'broken' | 'renegotiated';
  ownerId: string;
  ownerName: string;
  completionEvidence?: string;
  riskIfMissed?: string;
  createdAt: string;
  updatedAt: string;
}

export interface WaitingItemRecord {
  id: string;
  whatIsNeeded: string;
  owedByName: string;
  owedByContactId?: string;
  dateRequested: string;
  dueDate?: string;
  lastFollowUp?: string;
  nextFollowUpDate?: string;
  clientId?: string;
  clientName?: string;
  projectId?: string;
  escalationLevel: number;
  sourceLinks: SourceLink[];
  status: 'open' | 'received' | 'escalated' | 'cancelled';
  followUpTaskId?: string;
  createdAt: string;
  updatedAt: string;
}

export interface RiskIssueRecord {
  id: string;
  kind: 'risk' | 'issue' | 'blocker';
  description: string;
  severity: RiskSeverity;
  probability?: number;
  impact?: string;
  ownerId: string;
  ownerName: string;
  mitigationPlan?: string;
  dueDate?: string;
  clientId?: string;
  clientName?: string;
  projectId?: string;
  status: 'open' | 'mitigating' | 'resolved' | 'accepted';
  escalation?: string;
  ownerDecisionRequired: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface DeliverableRecord {
  id: string;
  name: string;
  clientId?: string;
  clientName?: string;
  projectId?: string;
  ownerId: string;
  ownerName: string;
  dueDate?: string;
  status: 'planned' | 'draft' | 'in_review' | 'approved' | 'delivered' | 'accepted';
  draftLocation?: string;
  finalLocation?: string;
  reviewStatus?: string;
  approvalStatus?: string;
  deliveryDate?: string;
  deliveryEvidence?: string;
  clientAcknowledgment?: string;
  sourceLinks: SourceLink[];
  createdAt: string;
  updatedAt: string;
}

export interface InboxItemRecord {
  id: string;
  title: string;
  summary?: string;
  classification: InboxClassification;
  confidence: number;
  status: 'pending' | 'processed' | 'dismissed' | 'snoozed';
  clientId?: string;
  clientName?: string;
  projectId?: string;
  sourceLinks: SourceLink[];
  suggestedAction?: string;
  createdTaskId?: string;
  createdAt: string;
  updatedAt: string;
  processedAt?: string;
}

export interface TeamMemberRecord {
  id: string;
  name: string;
  email?: string;
  role: string;
  kind: 'person' | 'agent' | 'contractor';
  active: boolean;
  capacityHoursPerWeek?: number;
}

export interface AgentWorkRecord {
  id: string;
  agentId: string;
  agentName: string;
  role: string;
  mission?: string;
  currentTaskId?: string;
  currentTaskTitle?: string;
  status: 'idle' | 'working' | 'blocked' | 'awaiting_approval' | 'failed' | 'completed';
  startTime?: string;
  lastActivityAt?: string;
  output?: string;
  errors?: string;
  blockers?: string;
  approvalNeeded: boolean;
  completionEvidence?: string;
  nextPlannedAction?: string;
  usageCost?: number;
  updatedAt: string;
}

export interface ProjectTemplateRecord {
  id: string;
  name: string;
  projectType: ProjectType;
  phases: string[];
  milestones: Array<{ title: string; offsetDays: number }>;
  tasks: Array<{
    title: string;
    priority: TaskPriority;
    offsetDays: number;
    estimatedMinutes?: number;
  }>;
  requiredDocuments: string[];
  defaultOwnerRole?: string;
  deliverables: string[];
  approvalGates: string[];
}

export interface PmStoreSnapshot {
  version: 1;
  projects: ProjectRecord[];
  tasks: TaskRecord[];
  milestones: MilestoneRecord[];
  decisions: DecisionRecord[];
  commitments: CommitmentRecord[];
  waitingItems: WaitingItemRecord[];
  risksIssues: RiskIssueRecord[];
  deliverables: DeliverableRecord[];
  inbox: InboxItemRecord[];
  team: TeamMemberRecord[];
  agents: AgentWorkRecord[];
  templates: ProjectTemplateRecord[];
  activity: ActivityEvent[];
  lastBootstrapAt?: string;
  lastExtractionAt?: string;
}

export interface CommandCenterPayload {
  generatedAt: string;
  date: string;
  businessHealth: {
    activeProjects: number;
    atRiskProjects: number;
    openTasks: number;
    overdueTasks: number;
    waitingItems: number;
    openCommitments: number;
    decisionsNeeded: number;
    clientsNeedingAttention: number;
    avgClientCompleteness?: number;
  };
  criticalAlerts: Array<{ id: string; severity: string; title: string; href?: string }>;
  ownerApprovals: TaskRecord[];
  topPriorities: TaskRecord[];
  myDay: {
    meetings: Array<{ id: string; title: string; at?: string; clientName?: string }>;
    criticalTasks: TaskRecord[];
    dueToday: TaskRecord[];
    overdue: TaskRecord[];
    waitingFollowUps: WaitingItemRecord[];
    decisionsNeeded: DecisionRecord[];
  };
  clientAttention: {
    atRisk: Array<{ id: string; name: string; reason: string }>;
    waitingOnUs: WaitingItemRecord[];
    waitingOnClient: WaitingItemRecord[];
    upcomingDeadlines: TaskRecord[];
    outstandingDeliverables: DeliverableRecord[];
    opportunities: Array<{ id: string; name: string; detail: string }>;
  };
  teamAndAgents: {
    teamWorkload: Array<{
      id: string;
      name: string;
      openTasks: number;
      overdue: number;
      blocked: number;
    }>;
    agentActivity: AgentWorkRecord[];
    lateTasks: TaskRecord[];
    approvalRequests: TaskRecord[];
  };
  projects: {
    atRisk: ProjectRecord[];
    upcomingMilestones: MilestoneRecord[];
    noRecentActivity: ProjectRecord[];
    lackingNextAction: ProjectRecord[];
  };
  weeklyCeoReview?: WeeklyCeoReview;
}

export interface WeeklyCeoReview {
  generatedAt: string;
  wins: string[];
  missedCommitments: string[];
  overdueWork: string[];
  clientRisks: string[];
  majorDecisions: string[];
  projectHealth: string[];
  strategicPriorities: string[];
  nextWeekOutcomes: string[];
  teamNotes: string[];
  agentNotes: string[];
}

export interface MyWorkPayload {
  today: TaskRecord[];
  overdue: TaskRecord[];
  dueThisWeek: TaskRecord[];
  upcoming: TaskRecord[];
  waitingOnOthers: TaskRecord[];
  needsOwnerDecision: TaskRecord[];
  highValueOpportunities: TaskRecord[];
  clientEmergencies: TaskRecord[];
  followUps: WaitingItemRecord[];
  recentlyCompleted: TaskRecord[];
  suggestedNextActions: string[];
  autoGenerated: TaskRecord[];
  delegatedToAgents: TaskRecord[];
  delegatedToTeam: TaskRecord[];
  requiringApproval: TaskRecord[];
}
