/**
 * Phase 6A synthetic website fixtures — not live Production sites.
 */

import type {
  ContentBlockRecord,
  FormInventoryRecord,
  MediaAssetRecord,
  WebsitePageRecord,
  WebsiteRegistryRecord,
} from './schemas.ts';
import { WEBSITE_STUDIO_BANNER, WEBSITE_STUDIO_NO_DEPLOY } from './schemas.ts';

export function syntheticWebsiteFixtures(): WebsiteRegistryRecord[] {
  const now = new Date().toISOString();
  return [
    {
      websiteId: 'ws_hvcg_demo',
      websiteName: 'High Value Capital Group (Synthetic)',
      businessEntity: 'High Value Capital Group',
      productionUrl: 'https://example-hvcg-synthetic.local',
      stagingUrl: 'https://staging-hvcg-synthetic.local',
      repositoryUrl: null,
      localRepositoryPath: null,
      framework: 'Next.js',
      hostingProvider: 'Azure Static Web Apps (synthetic)',
      productionBranch: 'main',
      defaultDevelopmentBranch: 'feature/website-studio-local',
      buildCommand: 'npm run build',
      testCommand: 'npm test',
      previewCommand: 'npm run dev -- --port 5199',
      deploymentMethod: 'SWA (scaffolded only)',
      contentArchitecture: 'MDX + React page modules',
      seoArchitecture: 'next-seo + JSON-LD',
      analyticsProvider: 'Synthetic analytics',
      formProvider: 'Synthetic forms',
      status: 'Discovered',
      lastSuccessfulDeployment: null,
      lastRollbackPoint: null,
      openChangeRequestCount: 0,
      repositoryHealth: 'Unknown',
      notes: `${WEBSITE_STUDIO_BANNER}; ${WEBSITE_STUDIO_NO_DEPLOY}; fixture only`,
      synthetic: true,
      mannyConfirmedRegistration: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      websiteId: 'ws_lvac_demo',
      websiteName: 'Las Vegas Appraisal Company (Synthetic)',
      businessEntity: 'Las Vegas Appraisal Company',
      productionUrl: 'https://example-lvac-synthetic.local',
      stagingUrl: null,
      repositoryUrl: null,
      localRepositoryPath: null,
      framework: 'Vite/React',
      hostingProvider: 'Synthetic host',
      productionBranch: 'main',
      defaultDevelopmentBranch: 'feature/website-studio-local',
      buildCommand: 'npm run build',
      testCommand: 'npm run test',
      previewCommand: 'npm run dev -- --port 5201',
      deploymentMethod: 'Scaffolded only',
      contentArchitecture: 'React components + content JSON',
      seoArchitecture: 'react-helmet-async',
      analyticsProvider: null,
      formProvider: 'Synthetic contact form',
      status: 'Registered',
      lastSuccessfulDeployment: null,
      lastRollbackPoint: null,
      openChangeRequestCount: 0,
      repositoryHealth: 'Unknown',
      notes: 'Synthetic fixture — not a live repository registration',
      synthetic: true,
      mannyConfirmedRegistration: true,
      createdAt: now,
      updatedAt: now,
    },
  ];
}

export function syntheticPagesFor(websiteId: string): WebsitePageRecord[] {
  const now = new Date().toISOString();
  if (websiteId === 'ws_hvcg_demo') {
    return [
      {
        pageId: 'pg_hvcg_home',
        websiteId,
        route: '/',
        pageTitle: 'High Value Capital Group',
        pageType: 'home',
        sourceFile: 'app/page.tsx',
        layout: 'app/layout.tsx',
        status: 'Published',
        lastModified: now,
        seoTitle: 'HVCG — Capital Advisory',
        metaDescription: 'Enterprise value and capital advisory for growth-minded operators.',
        canonicalUrl: 'https://example-hvcg-synthetic.local/',
        h1: 'Capital Advisory for High-Value Operators',
        majorSections: ['Hero', 'Services', 'Trust', 'CTA'],
        ctaLabels: ['Schedule a Consultation'],
        formsPresent: ['contact-hero'],
        imagesUsed: ['/media/hero-desk.jpg'],
        schemaMarkupPresent: true,
        structuredDataType: 'Organization',
        publishState: 'synthetic-published',
      },
      {
        pageId: 'pg_hvcg_about',
        websiteId,
        route: '/about',
        pageTitle: 'About HVCG',
        pageType: 'about',
        sourceFile: 'app/about/page.tsx',
        layout: 'app/layout.tsx',
        status: 'Published',
        lastModified: now,
        seoTitle: 'About High Value Capital Group',
        metaDescription: 'About HVCG capital advisory.',
        canonicalUrl: 'https://example-hvcg-synthetic.local/about',
        h1: 'About HVCG',
        majorSections: ['Story', 'Team', 'Approach'],
        ctaLabels: ['Contact Us'],
        formsPresent: [],
        imagesUsed: [],
        schemaMarkupPresent: false,
        structuredDataType: null,
        publishState: 'synthetic-published',
      },
      {
        pageId: 'pg_hvcg_services',
        websiteId,
        route: '/services',
        pageTitle: 'Services',
        pageType: 'services',
        sourceFile: 'app/services/page.tsx',
        layout: 'app/layout.tsx',
        status: 'Published',
        lastModified: now,
        seoTitle: 'HVCG Services',
        metaDescription: 'Capital readiness, enterprise value, and advisory services.',
        canonicalUrl: 'https://example-hvcg-synthetic.local/services',
        h1: 'Advisory Services',
        majorSections: ['Services grid', 'FAQ', 'CTA'],
        ctaLabels: ['Schedule a Consultation'],
        formsPresent: [],
        imagesUsed: ['/media/services.jpg'],
        schemaMarkupPresent: true,
        structuredDataType: 'FAQPage',
        publishState: 'synthetic-published',
      },
    ];
  }
  return [
    {
      pageId: 'pg_lvac_home',
      websiteId,
      route: '/',
      pageTitle: 'Las Vegas Appraisal Company',
      pageType: 'home',
      sourceFile: 'src/pages/Home.tsx',
      layout: 'src/layouts/MainLayout.tsx',
      status: 'Published',
      lastModified: now,
      seoTitle: 'Las Vegas Appraisal Company',
      metaDescription: 'Professional appraisal services in Las Vegas.',
      canonicalUrl: 'https://example-lvac-synthetic.local/',
      h1: 'Trusted Las Vegas Appraisals',
      majorSections: ['Hero', 'Services', 'Contact'],
      ctaLabels: ['Request Appraisal'],
      formsPresent: ['contact'],
      imagesUsed: ['/assets/office.jpg'],
      schemaMarkupPresent: true,
      structuredDataType: 'LocalBusiness',
      publishState: 'synthetic-published',
    },
  ];
}

export function syntheticBlocksFor(websiteId: string): ContentBlockRecord[] {
  const pages = syntheticPagesFor(websiteId);
  const home = pages[0];
  if (!home) return [];
  return [
    {
      blockId: `blk_${websiteId}_headline`,
      websiteId,
      pageId: home.pageId,
      blockType: 'headline',
      sourceFile: home.sourceFile,
      sourceLocation: 'hero.h1',
      currentValue: home.h1 || 'Headline',
      proposedValue: null,
      characterCount: (home.h1 || '').length,
      lastModified: home.lastModified,
      changeRequestId: null,
      aiGenerated: false,
      mannyApproved: true,
      validationStatus: 'Valid',
    },
    {
      blockId: `blk_${websiteId}_cta`,
      websiteId,
      pageId: home.pageId,
      blockType: 'CTA',
      sourceFile: home.sourceFile,
      sourceLocation: 'hero.cta',
      currentValue: home.ctaLabels[0] || 'Learn More',
      proposedValue: null,
      characterCount: (home.ctaLabels[0] || '').length,
      lastModified: home.lastModified,
      changeRequestId: null,
      aiGenerated: false,
      mannyApproved: true,
      validationStatus: 'Valid',
    },
    {
      blockId: `blk_${websiteId}_footer_phone`,
      websiteId,
      pageId: home.pageId,
      blockType: 'contact information',
      sourceFile: 'components/Footer.tsx',
      sourceLocation: 'footer.phone',
      currentValue: '(702) 555-0100',
      proposedValue: null,
      characterCount: 14,
      lastModified: home.lastModified,
      changeRequestId: null,
      aiGenerated: false,
      mannyApproved: true,
      validationStatus: 'Valid',
    },
  ];
}

export function syntheticMediaFor(websiteId: string): MediaAssetRecord[] {
  return [
    {
      mediaId: `media_${websiteId}_1`,
      websiteId,
      filename: websiteId === 'ws_hvcg_demo' ? 'hero-desk.jpg' : 'office.jpg',
      fileType: 'image/jpeg',
      dimensions: '1600x900',
      sizeBytes: 240_000,
      altText: websiteId === 'ws_hvcg_demo' ? 'Advisory workspace' : null,
      pagesUsed: ['/'],
      unused: false,
      proposedReplacement: null,
      compressionRecommendation: 'Consider WebP under 150KB',
      duplicateOf: null,
      missingAltText: websiteId !== 'ws_hvcg_demo',
    },
  ];
}

export function syntheticFormsFor(websiteId: string): FormInventoryRecord[] {
  return [
    {
      formId: `form_${websiteId}_contact`,
      websiteId,
      formName: 'Contact',
      pageId: syntheticPagesFor(websiteId)[0]?.pageId || null,
      sourceFile: 'components/ContactForm.tsx',
      fields: [
        { name: 'name', label: 'Full name', required: true },
        { name: 'email', label: 'Email', required: true },
        { name: 'message', label: 'Message', required: false },
      ],
      requiredFields: ['name', 'email'],
      submissionEndpoint: '/api/synthetic-contact',
      successBehavior: 'Show thank-you copy',
      spamProtection: 'honeypot',
      analyticsEvent: 'contact_submit',
      currentIntegration: 'Synthetic only',
      status: 'Active (synthetic)',
      endpointIsHighRisk: true,
    },
  ];
}
