import type { AdminAreaMeta } from './types';

export const ADMIN_AREAS: AdminAreaMeta[] = [
  {
    id: 'organizations',
    title: 'Organizations',
    description: 'Legal entities and firm organizations that own teams and users.',
    impact: 'Changing organizations affects who can be assigned and how access is grouped.',
    group: 'People & access',
    systemConfig: true,
    keywords: ['org', 'entity', 'firm'],
  },
  {
    id: 'clients',
    title: 'Client access',
    description: 'Which staff can open each client workspace.',
    impact: 'Grants control visibility of client documents and delivery data.',
    group: 'People & access',
    systemConfig: true,
    keywords: ['client', 'workspace', 'access'],
  },
  {
    id: 'users',
    title: 'Users',
    description: 'Invite, activate, and disable people who use Atlas.',
    impact: 'Disabled users lose product access; invites notify new staff.',
    group: 'People & access',
    systemConfig: true,
    keywords: ['user', 'invite', 'disable', 'staff'],
  },
  {
    id: 'roles',
    title: 'Roles',
    description: 'Named roles mapped to Entra groups and permissions.',
    impact: 'Role changes immediately change what people can do in Atlas.',
    group: 'People & access',
    systemConfig: true,
    keywords: ['role', 'entra', 'group'],
  },
  {
    id: 'permissions',
    title: 'Permissions',
    description: 'Approved capability catalog. You cannot invent unrestricted powers.',
    impact: 'Editing role permissions is high impact and is audited.',
    group: 'People & access',
    systemConfig: true,
    keywords: ['permission', 'capability', 'rbac'],
  },
  {
    id: 'teams',
    title: 'Teams',
    description: 'Working groups inside a business unit.',
    impact: 'Team membership can drive default assignments and filters.',
    group: 'People & access',
    systemConfig: false,
    keywords: ['team', 'group'],
  },
  {
    id: 'business-units',
    title: 'Business units',
    description: 'Divisions under an organization (e.g. Capital, Delivery).',
    impact: 'Used for reporting rollups and team placement.',
    group: 'People & access',
    systemConfig: true,
    keywords: ['business unit', 'division'],
  },
  {
    id: 'status-values',
    title: 'Status values',
    description: 'Client and project status pick lists.',
    impact: 'Affects pipelines, filters, and reporting groupings.',
    group: 'Reference data',
    systemConfig: false,
    keywords: ['status', 'stage', 'pipeline'],
  },
  {
    id: 'categories',
    title: 'Categories',
    description: 'General categorization labels for work items.',
    impact: 'Changes how lists and reports are labeled.',
    group: 'Reference data',
    systemConfig: false,
    keywords: ['category', 'tag'],
  },
  {
    id: 'referral-sources',
    title: 'Referral sources',
    description: 'Where leads and opportunities came from.',
    impact: 'Used in CRM reporting; inactive sources stop appearing in new forms.',
    group: 'Reference data',
    systemConfig: false,
    keywords: ['referral', 'source', 'lead'],
  },
  {
    id: 'service-types',
    title: 'Service types',
    description: 'Services HVCG offers to clients.',
    impact: 'Shapes engagement setup and proposal options.',
    group: 'Reference data',
    systemConfig: false,
    keywords: ['service', 'offering'],
  },
  {
    id: 'engagement-types',
    title: 'Engagement types',
    description: 'Engagement patterns (retainer, project, success fee, etc.).',
    impact: 'Affects financial and delivery templates.',
    group: 'Reference data',
    systemConfig: false,
    keywords: ['engagement', 'retainer'],
  },
  {
    id: 'document-categories',
    title: 'Document categories',
    description: 'Folders and labels for client document libraries.',
    impact: 'Does not rename existing SharePoint folders automatically.',
    group: 'Reference data',
    systemConfig: false,
    keywords: ['document', 'folder', 'library'],
  },
  {
    id: 'notification-preferences',
    title: 'Notification preferences',
    description: 'Reminders and alert defaults for the firm.',
    impact: 'Changes when people are notified about renewals and documents.',
    group: 'Configuration',
    systemConfig: false,
    keywords: ['notification', 'email', 'reminder'],
  },
  {
    id: 'workflow-settings',
    title: 'Workflow settings',
    description: 'Automation and escalation preferences.',
    impact: 'Can create tasks automatically and block live client communications.',
    group: 'Configuration',
    systemConfig: true,
    keywords: ['workflow', 'automation', 'escalation'],
  },
  {
    id: 'financial-settings',
    title: 'Financial settings',
    description: 'Currency and fee visibility defaults.',
    impact: 'May change who can see fee and invoice amounts in the product.',
    group: 'Configuration',
    systemConfig: true,
    keywords: ['finance', 'currency', 'fee', 'invoice'],
  },
  {
    id: 'capital-advisory-settings',
    title: 'Capital-advisory settings',
    description: 'Capital desk defaults and outreach guards.',
    impact: 'Affects capital package defaults and lender outreach controls.',
    group: 'Configuration',
    systemConfig: true,
    keywords: ['capital', 'lender', 'desk'],
  },
  {
    id: 'enterprise-value-assumptions',
    title: 'Enterprise-value assumptions',
    description: 'Default multiples and rates for EVA worksheets.',
    impact: 'Changes defaults for new analyses; does not rewrite past valuations.',
    group: 'Configuration',
    systemConfig: true,
    keywords: ['eva', 'enterprise value', 'multiple'],
  },
  {
    id: 'ai-settings',
    title: 'AI settings',
    description: 'AI queue and insight preferences. API keys are never managed here.',
    impact: 'Controls visibility of AI features for staff—not model credentials.',
    group: 'Configuration',
    systemConfig: true,
    keywords: ['ai', 'copilot', 'queue'],
  },
  {
    id: 'integrations',
    title: 'Integrations',
    description: 'Health of connected Microsoft services. No secrets shown.',
    impact: 'Review failures here; credential rotation stays in Entra / Key Vault.',
    group: 'Operations',
    systemConfig: true,
    keywords: ['integration', 'failed', 'connector'],
  },
  {
    id: 'feature-flags',
    title: 'Feature flags',
    description: 'Approved product features that can be turned on or off.',
    impact: 'Outbound and premium features require confirmation before enabling.',
    group: 'System',
    systemConfig: true,
    keywords: ['flag', 'feature', 'toggle'],
  },
  {
    id: 'audit-history',
    title: 'Audit history',
    description: 'Read-only log of administrative changes.',
    impact: 'View only. Use this to verify who changed what.',
    group: 'Operations',
    systemConfig: true,
    keywords: ['audit', 'log', 'history'],
  },
  {
    id: 'application-settings',
    title: 'Application settings',
    description: 'Nontechnical product labels, locale, and naming defaults.',
    impact: 'Affects display names and defaults across Atlas.',
    group: 'System',
    systemConfig: true,
    keywords: ['app', 'locale', 'timezone', 'settings'],
  },
];

export function getArea(id: string): AdminAreaMeta | undefined {
  return ADMIN_AREAS.find((a) => a.id === id);
}

export function searchAreas(query: string): AdminAreaMeta[] {
  const q = query.trim().toLowerCase();
  if (!q) return ADMIN_AREAS;
  return ADMIN_AREAS.filter(
    (a) =>
      a.title.toLowerCase().includes(q) ||
      a.description.toLowerCase().includes(q) ||
      a.keywords.some((k) => k.includes(q)) ||
      a.group.toLowerCase().includes(q),
  );
}
