import {
  ASK_ATLAS_QUESTION,
  type AskAtlasAnswer,
} from '../integrations/hub/askAtlas';

/** Signed Hub picture for Elite tests. No amounts, LTV, or invented At Risk on Colorado Beef. */
export const SIGNED_ASK_ATLAS_FIXTURE: AskAtlasAnswer = {
  kind: 'ask_atlas_attention_v1',
  question: ASK_ATLAS_QUESTION,
  invented: false,
  honestEmpty: false,
  ranking: ['At Risk', 'Overdue', 'Decision Required', 'Capital', 'Waiting', 'Blocked'],
  items: [
    {
      id: 'at-risk-pdg01',
      state: 'At Risk',
      why: 'Review recovered past-due invoice filenames together with capital-packet filenames. Amounts, payment status, and funding status were not extracted.',
      basedOn: 'Filename-derived Past Due Invoice and Capital_Acquisition packet for Prodigy Games.',
      evidence: 'Filename-derived Past Due Invoice and Capital_Acquisition packet for Prodigy Games.',
      provenance: 'LIKELY',
      classification: 'LIKELY',
      client: 'Prodigy Games',
      clientCode: 'PDG01',
      kind: 'hvs_actionable_at_risk',
    },
    {
      id: 'overdue-pdg01',
      state: 'Overdue',
      why: 'Review recovered past-due invoice filename. Payment status and amounts were not extracted.',
      basedOn: 'Past Due Invoice filename.',
      evidence: 'Past Due Invoice filename.',
      provenance: 'LIKELY',
      classification: 'LIKELY',
      client: 'Prodigy Games',
      clientCode: 'PDG01',
      kind: 'hvs_actionable_overdue',
    },
    {
      id: 'decision-ccb01',
      state: 'Decision Required',
      why: 'A recovered filename requires an operator decision. Do not invent Hub MI rows.',
      basedOn: 'SBA Express next-step filename. Lender-criteria strings are honesty denials, not invented criteria.',
      evidence: 'SBA Express next-step filename. Lender-criteria strings are honesty denials, not invented criteria.',
      provenance: 'PROPOSED',
      classification: 'PROPOSED',
      client: 'Colorado Beef',
      clientCode: 'CCB01',
      kind: 'hvs_actionable_decision',
    },
    {
      id: 'capital-ccb01',
      state: 'Capital',
      why: 'Review recovered capital-packet filename. Amounts, lender criteria, and funding status were not extracted.',
      basedOn: 'CONFIRMED filename Capital_Acquisition packet.',
      evidence: 'CONFIRMED filename Capital_Acquisition packet.',
      provenance: 'CONFIRMED',
      classification: 'CONFIRMED',
      client: 'Colorado Beef',
      clientCode: 'CCB01',
      kind: 'hvs_actionable_capital',
    },
    {
      id: 'waiting-ccb01',
      state: 'Waiting',
      why: 'Waiting on recovered filename evidence. Do not invent missing documents or amounts.',
      basedOn: 'Waiting filename evidence.',
      evidence: 'Waiting filename evidence.',
      provenance: 'PROPOSED',
      classification: 'PROPOSED',
      client: 'Colorado Beef',
      clientCode: 'CCB01',
      kind: 'hvs_actionable_waiting',
    },
  ],
  activity: {
    agent: 'atlas-hub-operator',
    missionKey: 'ATLAS-AGENTIC-OPS-ASK-ATTENTION-001',
    trigger: 'operator_operating_picture',
    timestamp: '2026-08-22T17:00:00.000Z',
    tools: ['operator_operating_picture', 'hvs_actionable_queues'],
    classification: 'LIKELY',
    result: 'answered',
  },
};

export const HONEST_EMPTY_ASK_ATLAS_FIXTURE: AskAtlasAnswer = {
  kind: 'ask_atlas_attention_v1',
  question: ASK_ATLAS_QUESTION,
  invented: false,
  honestEmpty: true,
  ranking: ['At Risk', 'Overdue', 'Decision Required', 'Capital', 'Waiting', 'Blocked'],
  items: [],
  activity: {
    agent: 'atlas-hub-operator',
    missionKey: 'ATLAS-AGENTIC-OPS-ASK-ATTENTION-001',
    trigger: 'operator_operating_picture',
    timestamp: '2026-08-22T17:00:00.000Z',
    tools: ['operator_operating_picture', 'hvs_actionable_queues'],
    classification: 'HONEST_EMPTY',
    result: 'honest_empty',
  },
};
